### ISSUE TITLE
Link in readme does not work

### ISSUE THREAD

**Issue by theendlessriver13** [gee-hydro/gee_monkey#1]
The link in the readme does not seem to work anymore, I get a 404
 https://github.com/kongdd/GEE_Tools/blob/master/gee_monkey.js
`2 Dashboard → New script → paste the script in gee_monkey → F5 refresh GEE website.`

Did the script move somewhere else?

**Comment by kongdd** [comment]
It is a paid version, not open source any more.

**Comment by theendlessriver13** [comment]
This is sad to hear.

**Comment by melanievt** [comment]
Indeed : ((

**Comment by theendlessriver13** [comment]
I hacked this (https://github.com/theendlessriver13/ee-task-start) together based on the open source code from this repo, maybe it helps you. It of course lacks some features gee_monkey has.

**Comment by kongdd** [comment]
10 USD is a reasonable price, if `gee_monkey` really works. It is rudeness hack my software by my public code snippet. 
At least, you need't to provoke the author saying: "Hi, I hacked you".
