### ISSUE TITLE
Google Earth Engine update to task manager

### ISSUE THREAD

**Issue by MichaelTD83** [gee-hydro/gee_monkey#2]
It seems that the task pane in GEE has been updated. Now any exports that go to the task pane are listed in an Unsubmitted section and have to be manually run, one by one, to be submitted. I believe because of this the tapermonkey extension/gee_monkey and the free code offered that gets pasted in the console no longer work. At least they do not for me. 

When the extension is run the console states "userscript.html?name=gee_monkey.user.js&id=5dd8ec0c-249e-4740-99e9-81a8e1eafec6:114 No task in the list ..."

When the free code is pasted in the console it states "undefined"

**Comment by czarmanu** [comment]
@MichaelTD83  I have the same issue

**Comment by MichaelTD83** [comment]
@czarmanu There are some helpful tips in this thread and it looks like the last comment may be a good temporary fix. I haven't tried it yet though. I just ended up holding down the control button on my PC and clicking each run individually.
https://groups.google.com/g/google-earth-engine-developers/c/T4es99oG0ao



//run this function in the chrome console to bulk run pending tasks.
//Then press F12 or Ctrl + Shift + J get into console, then paste those scripts in it, and press 
// * enter. All the task will be start automatically. 
```
runTasks = function() {
    $$('.run-button' ,$$('ee-task-pane')[0].shadowRoot).forEach(function(e) {
         e.click();
    })

    $$('ee-table-config-dialog, ee-image-config-dialog').forEach(function(e) {
    var eeDialog = $$('ee-dialog', e.shadowRoot)[0]
var paperDialog = $$('paper-dialog', eeDialog.shadowRoot)[0]
    $$('.ok-button', paperDialog)[0].click()
    })
}
```

**Comment by kongdd** [comment]
Script of `yzq.yang` works, 
```javascript
runTasks = function() {
    $$('.run-button' ,$$('ee-task-pane')[0].shadowRoot).forEach(function(e) {
         e.click();
    })

    $$('ee-table-config-dialog, ee-image-config-dialog').forEach(function(e) {
    var eeDialog = $$('ee-dialog', e.shadowRoot)[0]
var paperDialog = $$('paper-dialog', eeDialog.shadowRoot)[0]
    $$('.ok-button', paperDialog)[0].click()
    })
}
```
